name: Application Submit

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Script
        env:
          B12_SIGNING_SECRET: ${{ secrets.B12_SIGNING_SECRET }}
          B12_EMAIL: ${{ secrets.B12_EMAIL }}
          B12_RESUME: ${{ secrets.B12_RESUME }}
        run: python submit_script.py
